apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/hirenbhanushali/flux-charts
  ref:
    branch: main
  ignore: "README.md"
