apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app1
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./app1
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: flux-charts
      interval: 1m
  values:
    replicaCount: 2
